#!/usr/bin/env python3
"""Convert the linear Winkler L-panel mesh (``mesh_hex8.inp``, GC3D8/C3D8) into the quadratic
``mesh.inp`` (GC3D20R/C3D20R) used by the examples -- h-adaptivity refines HEX20-family elements only.

Midside nodes are shared between neighbouring elements (keyed by their two corner nodes) and use
the Abaqus HEX20 edge ordering. A midside node joins a node set iff both of its edge's corner nodes
are in that set; element sets are copied unchanged, as the element labels are kept. A node set
setBack is added for the back face z=0 (symmetry condition u_z=0 in the examples).

Usage: python hex8_to_hex20.py [mesh_hex8.inp] [mesh.inp]
"""

import sys

typeMap = {"GC3D8": "GC3D20R", "C3D8": "C3D20R"}
# Abaqus HEX20: nodes 9-12 on the bottom face edges, 13-16 on the top face edges, 17-20 vertical
edges = [(0, 1), (1, 2), (2, 3), (3, 0), (4, 5), (5, 6), (6, 7), (7, 4), (0, 4), (1, 5), (2, 6), (3, 7)]


def readBlocks(fileName):
    blocks, header = [], None
    for line in open(fileName):
        line = line.strip()
        if not line or line.startswith("**"):
            continue
        if line.startswith("*"):
            header = line
            blocks.append((header, []))
        else:
            parse = float if header.lower().startswith("*node") else int
            blocks[-1][1].append([parse(x) for x in line.split(",") if x.strip()])
    return blocks


def main(src="mesh_hex8.inp", dst="mesh.inp"):
    blocks = readBlocks(src)
    nodes = {}
    for header, rows in blocks:
        if header.lower().startswith("*node"):
            for row in rows:
                nodes[int(row[0])] = [float(x) for x in row[1:4]]

    nextLabel = max(nodes) + 1
    midside = {}

    def midNode(a, b):
        nonlocal nextLabel
        key = (min(a, b), max(a, b))
        if key not in midside:
            midside[key] = nextLabel
            nodes[nextLabel] = [0.5 * (p + q) for p, q in zip(nodes[a], nodes[b])]
            nextLabel += 1
        return midside[key]

    elementBlocks = []
    for header, rows in blocks:
        if header.lower().startswith("*element"):
            oldType = header.split("type=")[1].split(",")[0].strip()
            quadRows = [row + [midNode(row[1 + i], row[1 + j]) for i, j in edges] for row in rows]
            elementBlocks.append((header.replace(oldType, typeMap[oldType]), quadRows))

    with open(dst, "w") as f:
        f.write("** generated by hex8_to_hex20.py from {:}\n*node\n".format(src))
        for label in sorted(nodes):
            f.write("{:d}, {:.10g}, {:.10g}, {:.10g}\n".format(label, *nodes[label]))
        for header, rows in elementBlocks:
            f.write(header + "\n")
            for row in rows:
                # one line per element: EdelweissFE's parser has no Abaqus continuation lines
                f.write(", ".join(map(str, row)) + "\n")
        for header, rows in blocks:
            if header.lower().startswith("*elset"):
                labels = [x for row in rows for x in row]
            elif header.lower().startswith("*nset"):
                members = {x for row in rows for x in row}
                labels = sorted(members | {m for (a, b), m in midside.items() if a in members and b in members})
            else:
                continue
            f.write(header + "\n")
            for i in range(0, len(labels), 16):
                f.write(", ".join(map(str, labels[i : i + 16])) + "\n")

        # the back face z=0, supported in z by a symmetry condition in the examples
        zMin = min(c[2] for c in nodes.values())
        labels = sorted(label for label, c in nodes.items() if abs(c[2] - zMin) < 1e-9)
        f.write("*nSet, nSet=setBack\n")
        for i in range(0, len(labels), 16):
            f.write(", ".join(map(str, labels[i : i + 16])) + "\n")

    print("{:}: {:d} nodes, {:d} elements".format(dst, len(nodes), sum(len(r) for _, r in elementBlocks)))


if __name__ == "__main__":
    main(*sys.argv[1:])
